[project]
name = "GUI-gradebook-manager"
version = "3.0.0"
description = "A Tkinter and SQLite desktop application for managing student gradebooks and user accounts, featuring CRUD operations and CSV export."
readme = "README.md"
requires-python = ">=3.11.13"
dependencies = [
    "pandas>=2.3.1",
    "typing-extensions>=4.16.0",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.14.2",
    "ruff>=0.16.0",
]
